exclude: ^tests/.*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: (integration_tests/|\.md|test_error_rendering\.cpp)
    -   id: end-of-file-fixer
        exclude: (integration_tests/)
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: check-yaml
        exclude: ^(tests/|doc/)
    -   id: check-toml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args: [--autofix]
    -   id: debug-statements
        language_version: python3
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1
    hooks:
    -   id: clang-format
        args: [--style=file, -i]
        types_or: [c++, c]
        exclude: "(integration_tests/)"
